# Generated by Django 3.0.5 on 2020-11-11 02:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos_Bases',
            fields=[
                ('id_Archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=30)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos')),
                ('descripcion', models.CharField(max_length=100)),
                ('subida', models.DateField(default=datetime.datetime(2020, 11, 10, 20, 7, 34, 984388))),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['id_Archivo'],
            },
        ),
    ]
