# Generated by Django 3.0.5 on 2020-12-18 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0005_auto_20201218_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos_bases',
            name='nombre_archivo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='archivos_bases',
            name='subida',
            field=models.DateField(default=datetime.datetime(2020, 12, 18, 7, 31, 4, 347372)),
        ),
    ]
