# Generated by Django 3.0.5 on 2021-02-08 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0006_auto_20201218_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos_bases',
            name='subida',
            field=models.DateField(default=datetime.datetime(2021, 2, 8, 16, 59, 29, 764516)),
        ),
    ]
