# Generated by Django 3.0.5 on 2021-02-02 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrenamiento', '0008_imagenes_som'),
    ]

    operations = [
        migrations.CreateModel(
            name='red_neuronal',
            fields=[
                ('id_red', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('epoca', models.IntegerField()),
                ('pasos', models.IntegerField()),
                ('pasos_validacion', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('f1', models.IntegerField()),
                ('f2', models.IntegerField()),
                ('modelo', models.FileField(blank=True, null=True, upload_to='modelo')),
                ('pesos', models.FileField(blank=True, null=True, upload_to='pesos')),
                ('id_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.Data')),
                ('id_som', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.Entrenamiento_Som')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Red Neuronal',
                'verbose_name_plural': 'Redes Neuronales',
                'ordering': ['id_red'],
            },
        ),
    ]
