# Generated by Django 3.0.5 on 2021-02-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0008_imagenes_som'),
        ('red_neuronal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='red_neuronal',
            name='id_data',
        ),
        migrations.AddField(
            model_name='red_neuronal',
            name='id_data',
            field=models.ManyToManyField(to='entrenamiento.Data'),
        ),
        migrations.RemoveField(
            model_name='red_neuronal',
            name='id_som',
        ),
        migrations.AddField(
            model_name='red_neuronal',
            name='id_som',
            field=models.ManyToManyField(to='entrenamiento.Entrenamiento_Som'),
        ),
    ]
