# Generated by Django 3.0.5 on 2021-02-04 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0008_imagenes_som'),
        ('red_neuronal', '0003_auto_20210204_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='red_neuronal',
            name='id_data',
        ),
        migrations.RemoveField(
            model_name='red_neuronal',
            name='id_som',
        ),
        migrations.CreateModel(
            name='Som_red',
            fields=[
                ('id_Som_red', models.AutoField(primary_key=True, serialize=False)),
                ('id_Som', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.Entrenamiento_Som')),
                ('id_red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='red_neuronal.red_neuronal')),
            ],
            options={
                'verbose_name': 'R_Som',
                'verbose_name_plural': 'R_Soms',
                'ordering': ['id_Som_red'],
            },
        ),
        migrations.CreateModel(
            name='Data_red',
            fields=[
                ('id_Data_red', models.AutoField(primary_key=True, serialize=False)),
                ('id_Data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.Data')),
                ('id_red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='red_neuronal.red_neuronal')),
            ],
            options={
                'verbose_name': 'R_Data',
                'verbose_name_plural': 'R_Datas',
                'ordering': ['id_Data_red'],
            },
        ),
    ]
