# Generated by Django 3.0.5 on 2021-02-05 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red_neuronal', '0004_auto_20210204_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_red',
            fields=[
                ('id_datos', models.AutoField(primary_key=True, serialize=False)),
                ('acc', models.FloatField(max_length=4)),
                ('loss', models.FloatField(max_length=4)),
                ('val_acc', models.FloatField(max_length=4)),
                ('val_loss', models.FloatField(max_length=4)),
                ('id_red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_neuronal.red_neuronal')),
            ],
            options={
                'verbose_name': 'Datos red',
                'verbose_name_plural': 'Datos redes',
                'ordering': ['id_datos'],
            },
        ),
    ]
