# Generated by Django 3.0.5 on 2021-02-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_neuronal', '0005_datos_red'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_red',
            name='mse',
            field=models.FloatField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='datos_red',
            name='val_mse',
            field=models.FloatField(blank=True, max_length=4, null=True),
        ),
    ]
