# Generated by Django 3.0.5 on 2020-11-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=models.CharField(max_length=100),
        ),
    ]
