# Generated by Django 3.0.5 on 2020-12-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_auto_20201121_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
