# Generated by Django 3.0.5 on 2020-12-20 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id_Data', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Bases',
                'ordering': ['id_Data'],
            },
        ),
        migrations.CreateModel(
            name='Neurons',
            fields=[
                ('id_Neurons', models.AutoField(primary_key=True, serialize=False)),
                ('Canal1', models.FloatField()),
                ('Canal2', models.FloatField()),
                ('Canal3', models.FloatField()),
                ('Canal4', models.FloatField()),
            ],
            options={
                'verbose_name': 'Neurona',
                'verbose_name_plural': 'Neuronas',
                'ordering': ['id_Neurons'],
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id_ref', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('img_ref', models.ImageField(blank=True, null=True, upload_to='referencia')),
                ('img_normalizada', models.ImageField(blank=True, null=True, upload_to='normalizada_ref')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
                'ordering': ['id_ref'],
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('imagen_original', models.ImageField(blank=True, null=True, upload_to='original')),
                ('imagen_normalizada', models.ImageField(blank=True, null=True, upload_to='normalizada')),
                ('imagen_lab', models.ImageField(blank=True, null=True, upload_to='lab')),
                ('imagen_hsv', models.ImageField(blank=True, null=True, upload_to='hsv')),
                ('id_Data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.Data')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'ordering': ['id_imagen'],
            },
        ),
        migrations.CreateModel(
            name='Entrenamiento_Som',
            fields=[
                ('id_Entrenamiento_Som', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('k_iteracion', models.IntegerField()),
                ('umbral_minimo', models.FloatField(max_length=4)),
                ('umbral_par_media', models.FloatField(max_length=4)),
                ('umbral_fusion', models.FloatField(max_length=4)),
                ('umbral_poda', models.IntegerField()),
                ('umbral_neuronas', models.IntegerField()),
                ('canal1', models.IntegerField()),
                ('canal2', models.IntegerField()),
                ('canal3', models.IntegerField()),
                ('canal4', models.IntegerField()),
                ('id_Data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.Data')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrenamiento',
                'verbose_name_plural': 'Entrenamientos',
                'ordering': ['id_Entrenamiento_Som'],
            },
        ),
        migrations.AddField(
            model_name='data',
            name='id_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.Referencia'),
        ),
    ]
