# Generated by Django 3.0.5 on 2020-12-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neurons',
            name='id_Entrenamiento_Som',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.Entrenamiento_Som'),
        ),
    ]
