# Generated by Django 3.0.5 on 2021-01-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0003_neurons_k_iteracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamiento_som',
            name='umbral_fusion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entrenamiento_som',
            name='umbral_minimo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entrenamiento_som',
            name='umbral_par_media',
            field=models.IntegerField(),
        ),
    ]
