# Generated by Django 3.0.5 on 2021-01-19 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0004_auto_20210113_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenamiento_som',
            name='k_iteracion',
        ),
        migrations.RemoveField(
            model_name='neurons',
            name='k_iteracion',
        ),
    ]
