# Generated by Django 3.0.5 on 2021-01-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0005_auto_20210118_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento_som',
            name='modelo',
            field=models.FileField(blank=True, null=True, upload_to='modelo'),
        ),
        migrations.AddField(
            model_name='entrenamiento_som',
            name='pesos',
            field=models.FileField(blank=True, null=True, upload_to='pesos'),
        ),
    ]
