# Generated by Django 3.0.5 on 2021-02-02 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0007_auto_20210122_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes_Som',
            fields=[
                ('id_Imagen', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_Som')),
                ('id_som', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.Entrenamiento_Som')),
            ],
            options={
                'verbose_name': 'Imagen som',
                'verbose_name_plural': 'Imagenes som',
                'ordering': ['id_Imagen'],
            },
        ),
    ]
